export const goals = [
  {
    id: 'career-exploration',
    label: 'Career exploration',
    shortLabel: 'Explore',
    title: 'See where possibility begins.',
    caption: 'Find low-pressure places, real stories, and the first connector worth meeting.',
  },
  {
    id: 'interviewing',
    label: 'Interviewing skills',
    shortLabel: 'Interview',
    title: 'Practice before the real stakes arrive.',
    caption: 'Move from uncertainty to repetition, language, and calmer preparation.',
  },
  {
    id: 'network-confidence',
    label: 'Networking confidence',
    shortLabel: 'Confidence',
    title: 'Build comfort before you build a network.',
    caption: 'Start with peer-led spaces and story-rich conversations that lower the pressure.',
  },
  {
    id: 'internship-prep',
    label: 'Internship prep',
    shortLabel: 'Internship',
    title: 'Turn preparation into visible next steps.',
    caption: 'Mix guidance, revision, and events that make applications feel concrete.',
  },
]

export const identityOptions = [
  'First-year student',
  'Sophomore',
  'Junior transfer',
  'STEM senior',
  'Peer mentor attendee',
]

export const threadTags = [
  'Helpful question',
  'What surprised me',
  'Before you go',
  'What I wish I knew',
]

export const scenes = [
  {
    id: 'entry',
    label: 'Entry',
    eyebrow: 'Social capital',
    title: 'Find the places that open people up.',
    body: 'A warmer way to discover support, events, and lived advice before the moment matters.',
  },
  {
    id: 'build',
    label: 'Build',
    eyebrow: 'Momentum',
    title: 'What you want to build changes what should light up next.',
    body: 'Goals shape the route. The interface stays quiet until the right kind of opportunity is worth seeing.',
  },
  {
    id: 'map',
    label: 'Map',
    eyebrow: 'Explore',
    title: 'Then the campus starts to make sense.',
    body: 'Spaces and events arrive in sequence, with the most relevant opportunities rising first.',
  },
]

export const mapRegions = [
  {
    id: 'commons',
    label: 'Student Commons',
    x: '11%',
    y: '18%',
    width: '27%',
    height: '25%',
    tint: 'rgba(91, 138, 126, 0.28)',
  },
  {
    id: 'library-walk',
    label: 'Library Walk',
    x: '43%',
    y: '10%',
    width: '22%',
    height: '19%',
    tint: 'rgba(177, 145, 81, 0.26)',
  },
  {
    id: 'career-row',
    label: 'Career Row',
    x: '60%',
    y: '31%',
    width: '26%',
    height: '22%',
    tint: 'rgba(91, 126, 154, 0.26)',
  },
  {
    id: 'event-lawn',
    label: 'Event Lawn',
    x: '24%',
    y: '57%',
    width: '29%',
    height: '21%',
    tint: 'rgba(145, 87, 77, 0.24)',
  },
  {
    id: 'mentor-hill',
    label: 'Mentor Hill',
    x: '62%',
    y: '62%',
    width: '21%',
    height: '17%',
    tint: 'rgba(132, 101, 71, 0.24)',
  },
]

export const resources = [
  {
    id: 'success-office',
    title: 'First-Gen Success Office',
    type: 'space',
    area: 'Student Commons',
    chapter: 'grounding',
    x: '19%',
    y: '23%',
    goals: ['career-exploration', 'network-confidence'],
    tags: ['Belonging', 'Peer-led', 'Start here'],
    firstAction: 'Ask what resource students usually go to first when they feel unsure.',
    whyNow: 'A low-pressure first stop is often the fastest way to decode who can help next.',
    visualLabel: 'Welcome desk',
    peerThoughts: [
      {
        id: 'so-1',
        author: 'Junior transfer',
        tag: 'Before you go',
        copy: 'I said I was unsure what even counted as support. That gave me two clearer next places.',
      },
      {
        id: 'so-2',
        author: 'First-year student',
        tag: 'What surprised me',
        copy: 'It felt less like advising and more like finally learning who on campus actually opens doors.',
      },
    ],
  },
  {
    id: 'career-studio',
    title: 'Career Studio Drop-In',
    type: 'space',
    area: 'Career Row',
    chapter: 'craft',
    x: '68%',
    y: '39%',
    goals: ['career-exploration', 'interviewing', 'internship-prep'],
    tags: ['Drop-in', 'Materials', 'Planning'],
    firstAction: 'Bring one specific question so the visit stays concrete.',
    whyNow: 'The fastest confidence comes when help is tactical instead of abstract.',
    visualLabel: 'Open studio',
    peerThoughts: [
      {
        id: 'cs-1',
        author: 'Sophomore',
        tag: 'Helpful question',
        copy: 'I asked which part of my resume mattered most for a first internship. That focused the whole visit.',
      },
      {
        id: 'cs-2',
        author: 'STEM senior',
        tag: 'What I wish I knew',
        copy: 'One rewritten bullet was more useful than asking them to fix everything.',
      },
    ],
  },
  {
    id: 'peer-mentor-hub',
    title: 'Peer Mentor Hub',
    type: 'space',
    area: 'Mentor Hill',
    chapter: 'confidence',
    x: '71%',
    y: '70%',
    goals: ['network-confidence', 'career-exploration'],
    tags: ['Near-peer', 'Confidence', 'Reflection'],
    firstAction: 'Ask what first conversation felt most manageable for other students.',
    whyNow: 'Confidence barriers usually fall faster when another student names the move out loud.',
    visualLabel: 'Peer table',
    peerThoughts: [
      {
        id: 'pm-1',
        author: 'Peer mentor attendee',
        tag: 'Helpful question',
        copy: 'Seeing how someone else phrased their first email made networking feel much less mysterious.',
      },
      {
        id: 'pm-2',
        author: 'Sophomore',
        tag: 'Before you go',
        copy: 'I kept a screenshot of the question I wanted to ask. It helped when I froze.',
      },
    ],
  },
  {
    id: 'alumni-coffee',
    title: 'Alumni Coffee Chat Series',
    type: 'event',
    area: 'Event Lawn',
    chapter: 'confidence',
    x: '32%',
    y: '64%',
    goals: ['network-confidence', 'career-exploration'],
    tags: ['Event', 'Alumni', 'Stories'],
    firstAction: 'Open with one question about how they figured out what mattered early on.',
    whyNow: 'The easiest networking moment is often a story exchange, not a formal ask.',
    visualLabel: 'Story circle',
    peerThoughts: [
      {
        id: 'ac-1',
        author: 'Junior transfer',
        tag: 'What surprised me',
        copy: 'Asking what they wish they had known worked better than asking for a giant career answer.',
      },
      {
        id: 'ac-2',
        author: 'First-year student',
        tag: 'Before you go',
        copy: 'Going with one friend made the whole event feel lighter.',
      },
    ],
  },
  {
    id: 'mock-interview-night',
    title: 'Mock Interview Night',
    type: 'event',
    area: 'Library Walk',
    chapter: 'craft',
    x: '48%',
    y: '18%',
    goals: ['interviewing', 'internship-prep'],
    tags: ['Practice', 'Interview', 'Feedback'],
    firstAction: 'Write down the part of interviewing that usually throws you off before you start.',
    whyNow: 'Practice works best when it targets one stress point, not your whole identity.',
    visualLabel: 'Practice room',
    peerThoughts: [
      {
        id: 'mi-1',
        author: 'STEM senior',
        tag: 'What I wish I knew',
        copy: 'I got more out of it when I asked for feedback on one answer pattern.',
      },
      {
        id: 'mi-2',
        author: 'Sophomore',
        tag: 'Helpful question',
        copy: 'I asked how to pause without sounding unprepared. That changed the way I practiced.',
      },
    ],
  },
  {
    id: 'resume-lab',
    title: 'Resume and Story Lab',
    type: 'space',
    area: 'Library Walk',
    chapter: 'craft',
    x: '56%',
    y: '26%',
    goals: ['internship-prep', 'career-exploration'],
    tags: ['Writing', 'Resume', 'Storytelling'],
    firstAction: 'Bring one sentence that does not sound like you yet and ask how to make it more specific.',
    whyNow: 'Revision becomes more useful once the story underneath your draft starts to sharpen.',
    visualLabel: 'Revision corner',
    peerThoughts: [
      {
        id: 'rl-1',
        author: 'Junior transfer',
        tag: 'What surprised me',
        copy: 'They helped me turn a campus job into a story about initiative instead of just listing tasks.',
      },
      {
        id: 'rl-2',
        author: 'First-year student',
        tag: 'Before you go',
        copy: 'A messy draft was still much better than arriving empty-handed.',
      },
    ],
  },
]

export const chapterPanels = [
  {
    id: 'grounding',
    title: 'Ground first',
    body: 'Start where questions are welcome and the stakes stay low.',
  },
  {
    id: 'confidence',
    title: 'Hear real stories',
    body: 'Peer and alumni voices make the invisible rules easier to read.',
  },
  {
    id: 'craft',
    title: 'Practice in public',
    body: 'Materials, interviews, and language get easier once they become visible.',
  },
]
